# Generated by Django 3.2.18 on 2023-03-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('graduate_to', models.CharField(max_length=50)),
                ('employed', models.BooleanField(default=False)),
                ('ielts_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gre_score', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
