# Generated by Django 3.2.18 on 2023-03-24 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_articles', to='app_name.user'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.user')),
            ],
            options={
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(related_name='liked_articles', through='app_name.Like', to='app_name.User'),
        ),
    ]
