# Generated by Django 3.2.18 on 2023-03-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0004_auto_20230324_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
