# Generated by Django 3.2.18 on 2023-03-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0005_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.user')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
