# Generated by Django 3.2.18 on 2023-04-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0007_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_statement',
            field=models.CharField(default='This person is lazy and has not written anything.', max_length=255),
        ),
    ]
