# Generated by Django 3.2.18 on 2023-04-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0010_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='team_photos/default.png', upload_to='team_photos/')),
                ('area_of_responsibility', models.CharField(max_length=255)),
            ],
        ),
    ]
