# Generated by Django 3.2.18 on 2023-04-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0011_teamintroduction_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
