# Generated by Django 3.2.18 on 2023-04-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0012_alter_teammember_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_name.user')),
                ('task_statement', models.CharField(default='', max_length=255)),
                ('real_name', models.CharField(default='', max_length=50)),
            ],
            bases=('app_name.user',),
        ),
    ]
