# Generated by Django 3.2.18 on 2023-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0017_remove_article_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
