# Generated by Django 3.2.18 on 2023-04-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0019_remove_article_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_url', models.CharField(max_length=200)),
                ('admin_comment', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.article')),
            ],
        ),
    ]
