# Generated by Django 3.2.18 on 2023-04-22 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0020_selectedarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_name.article')),
                ('admin_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '精选文章',
                'verbose_name_plural': '精选文章',
            },
            bases=('app_name.article',),
        ),
        migrations.DeleteModel(
            name='SelectedArticle',
        ),
    ]
