# Generated by Django 3.2.18 on 2023-04-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0022_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
    ]
