# Generated by Django 3.2.18 on 2023-04-24 06:26

import app_name.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0023_article_is_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ielts_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('institution', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=False)),
                ('offer_image', models.ImageField(default='offers/default_offer.png', upload_to=app_name.models.get_upload_to)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_offers', to='app_name.user')),
            ],
            options={
                'ordering': ['offer_id'],
            },
        ),
    ]
