# Generated by Django 3.2.18 on 2023-04-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0024_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fans',
            field=models.ManyToManyField(related_name='idols', to='app_name.User'),
        ),
    ]
